### PR TITLE
Created new PasswordResetsController class

### PR DESCRIPTION
**Pull request by rkarakkadan**

### CODE REVIEW

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /describe

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /improve

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /analyze

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /analyse

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /analyse

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /Analyze

**Comment by rkarakkadan** [comment]
@CodiumAI-Agent /improve

**Comment by rkarakkadan** [comment]
tset

**Review by rkarakkadan — COMMENTED** [review]
@CodiumAI-Agent /improve

**Pull request closed without merging**
