### PR TITLE
Create new class PasswordResetsController.cs

### PR DESCRIPTION
**Pull request by rkarakkadan**

### CODE REVIEW

**Comment by r-karakkadan** [comment]
@CodiumAi-agent /describe

**Comment by r-karakkadan** [comment]
@codiumAi-Agent /ask

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /describe

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /Improve

**Comment by r-karakkadan** [comment]
@CodiumAI-Agent /analyse

**Comment by rkarakkadan** [comment]
@CodiumAI-Agent /analyse

**Pull request closed without merging**
